"""empty message

Revision ID: 1df079c4f58f
Revises: e532a346f1bd
Create Date: 2023-01-21 18:42:10.686656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df079c4f58f'
down_revision = 'e532a346f1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('release',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=240),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('release',
               existing_type=sa.String(length=240),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
